### ISSUE TITLE
Publish on modrinth.

### ISSUE THREAD

**Issue by art0007i** [KosmosPrime/journey-pac#1]
Awesome mod, but it would be nice if it was more easily discoverable.
I think publishing the mod on [modrinth](https://modrinth.com/) would be really useful for finding this mod and installing it using launchers that support doing that.

Currently searching "openpac journeymap" on google brings up your github profile, not even this specific repository, which makes it even more difficult to find.

**Comment by KosmosPrime** [comment]
I've created the project on modrinth, waiting for review. Will update once that's done.

**Comment by KosmosPrime** [comment]
There's now a [modrinth page](https://modrinth.com/mod/journey-pac).
