### ISSUE TITLE
Fabric/MultiLoader version

### ISSUE THREAD

**Issue by mysticdrew** [KosmosPrime/journey-pac#2]
Hey there, JourneyMap dev here. 
Thanks for your work on this mod, I had planned to do this eventually when I got time. Likely in the fall this year, but looks like I don't need to anymore! 

Any chance you could create a fabric version of this also? Possibly using [multiloader template](https://github.com/jaredlll08/MultiLoader-Template) to make it a bit simpler on your end? 

If you need help, feel free to reach out. 

here is an example mod using the journeymap api with multiloader template
https://github.com/TeamJM/journeymap-additions/tree/1.18.2

**Comment by KosmosPrime** [comment]
Quick update, looked at Multiloader and managed to get my existing code to compile using the forge side of it. I've never modded for fabric in any capacity so I'll have to see how porting works. The example uses Java services, but I'm not sure I use enough loader-independent functionality for this to work well.

**Comment by mysticdrew** [comment]
I don't use the Java ServiceLoader either. 
In JourneyMap, I use interfaces and implementations. 

Fabric api has many events to replace forge events, if they do not, you use mixins. 

My Forge and Fabric events call the common handler code. 
The only forge and fabric code I have in Journeymap are the entry points, and event listeners, be it mixins for loader/api events. Journeymap-additions does not really have an example of that. 

Reason I ask if you'd make a fabric version, is because I keep getting requests to support open parties for both fabric and forge versions. Then I found your projects, so that takes care of the forge version. 

Anyways, if feel free to pop into the JourneyMap discord and I can help you with the fabric side of things.

**Comment by KosmosPrime** [comment]
There is now a fabric version on [Modrinth](https://modrinth.com/mod/journey-pac/version/F5GKdD2I). I've yet to set up automatic publishing but that can wait for now.

**Comment by mysticdrew** [comment]
Thanks!
