### ISSUE TITLE
Being able to add and forceload claims via GUI

### ISSUE THREAD

**Issue by Fnige** [KosmosPrime/journey-pac#6]
Idk how possible this is but having the ability to add claims and forceload them via a gui within journeymap would be very good

I'm guessing the best method might to have a `claim chunk` and a `forceload chunk` option when right clicking a chunk but I'm not a developer

**Comment by KosmosPrime** [comment]
That's already possible. There's keybinds for claiming and forceloading chunks, you have to hold it down while dragging to select an area on the fullscreen map which gets claimed (or unclaimed, when dragging with RMB).
